### PR TITLE
Remove blobber pools

### PR DESCRIPTION
**Pull request by Sriep**
### Changes
-

### Fixes
-

### Tests
Tasks to complete before merging PR:
- [ ]  Ensure system tests are passing. If not [Run them manually](https://github.com/0chain/gosdk/actions/workflows/system_tests.yml) to check for any regressions :clipboard:
- [ ]  Do any new system tests need added to test this change? do any existing system tests need updated? If so create a PR at [0chain/system_test](https://github.com/0chain/system_test)
- [ ]  Merge your system tests PR to master AFTER merging this PR

### Associated PRs (Link as appropriate):
- blobber:
- 0chain: https://github.com/0chain/0chain/pull/1313
- system_test: https://github.com/0chain/system_test/pull/279
- zboxcli: https://github.com/0chain/zboxcli/pull/239
- zwalletcli:
- Other: ...

### CODE REVIEW

**Comment by service-0chain** [comment]
Manual system tests [failure] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | FALSE  |
| system-tests  | remove_bloober_pools  |
| gosdk  | remove_blobber_pools  |
| zboxcli  | staging  |
| zwalletcli  | staging  |
| 0chain  | remove_blobbers  |
| blobber  | staging  |
| authorizer  | staging  |
| 0box  | staging  |
| 0block  | staging  |
| 0dns  | staging  |
| explorer  | staging  |
| 0proxy  | staging  |
| 0search  | staging  |

**Comment by service-0chain** [comment]
Manual system tests [failure] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | FALSE  |
| system-tests  | remove_bloober_pools  |
| gosdk  | remove_blobber_pools  |
| zboxcli  | staging  |
| zwalletcli  | staging  |
| 0chain  | blobber_pools  |
| blobber  | staging  |
| authorizer  | staging  |
| 0box  | staging  |
| 0block  | staging  |
| 0dns  | staging  |
| explorer  | staging  |
| 0proxy  | staging  |
| 0search  | staging  |

**Comment by service-0chain** [comment]
Manual system tests [failure] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | FALSE  |
| system-tests  | remove_bloober_pools  |
| gosdk  | remove_blobber_pools  |
| zboxcli  | blobber_pools  |
| zwalletcli  | staging  |
| 0chain  | blobber_pools  |
| blobber  | staging  |
| authorizer  | staging  |
| 0box  | staging  |
| 0block  | staging  |
| 0dns  | staging  |
| explorer  | staging  |
| 0proxy  | staging  |
| 0search  | staging  |

**Review by peterlimg — APPROVED** [review]
lgtm

**Comment by Sriep** [comment]
Replaed by https://github.com/0chain/gosdk/pull/490

**Pull request closed without merging**
