### PR TITLE
Sync jssdk with staging branch

### PR DESCRIPTION
**Pull request by rizary**
This PR attempt to merge jssdk into staging branch to avoid commit gap between them. This should be merge first, because it will be hard if the gap is bigger.

@moldis @cnlangzi @mallochine

### CODE REVIEW

**Comment by rizary** [comment]
@mallochine Do you mind to take a look for the PR?

**Comment by mallochine** [comment]
@Rizary  what am I supposed to be checking?

**Comment by mallochine** [comment]
IDK just make sure this thing passes `go test github.com/0chain/gosdk/core/zcncrypto`

**Comment by rizary** [comment]
@mallochine as per our discussion in the slack channel with @guruhubb and others. Instead of giving you the tar, I finally able to create the branch and try open the PR.

It still won't pass the zcncrypto. Let me see what I can do.

Thanks!

**Review by cnlangzi — APPROVED** [review]
tested it on local block-explorer. it works.

**Comment by shaktals** [comment]
On [these lines](https://github.com/0chain/gosdk/pull/261/files#diff-9009ffebe1262f9d2e737588724de814209499494e55f8ed9acc19219ded1e9dL37-L43) we have two typos. It should say 'phrase', it says 'phase'.

**Review by moldis — APPROVED** [review]
Looks good

**Pull request merged**
