### PR TITLE
Default client config

### PR DESCRIPTION
**Pull request by Dmdv**
## New features:

Prior to start working with the bridge, a client must have configuration in the default folder.
Owner of the bridge deployed in Ethereum must have configuration in order to add authorizers in Ethereum blockchain.

This PR adds generation of configuration for 2 types of WZCN clients: 
1. WZCN client default configuration
2. WZCN bridge owner default configuration

Example:

```golang
	zcnbridge.CreateInitialClientConfig(
		"bridge.yaml",
		"0x860FA46F170a87dF44D7bB867AA4a5D2813127c1",
		"0xF26B52df8c6D9b9C20bfD7819Bed75a75258c7dB",
		"0x930E1BE76461587969Cb7eB9BFe61166b1E70244",
		"https://ropsten.infura.io/v3/22cb2849f5f74b8599f3dc2a23085bd4",
		"password",
		300000,
		0,
		75.0,
	)

	zcnbridge.CreateInitialOwnerConfig(
		"owner.yaml",
		"0x860FA46F170a87dF44D7bB867AA4a5D2813127c1",
		"0xF26B52df8c6D9b9C20bfD7819Bed75a75258c7dB",
		"0x930E1BE76461587969Cb7eB9BFe61166b1E70244",
		"0xFE20Ce9fBe514397427d20C91CB657a4478A0FFa",
		"https://ropsten.infura.io/v3/22cb2849f5f74b8599f3dc2a23085bd4",
		"password",
		300000,
		0,
	)
```

This will create corresponding config files in `~/.zcn` folder
1. bridge.yaml
2. owner.yaml

Example config files:

```yaml
# bridge owner config
owner:
    # KeyStorage unlock storage
    Password: password
    # User's Ethereum address (should be registered in the local key storage)
    EthereumAddress: 0x860FA46F170a87dF44D7bB867AA4a5D2813127c1
    # Address of Ethereum bridge contract
    BridgeAddress: 0xF26B52df8c6D9b9C20bfD7819Bed75a75258c7dB
    # Address of Ethereum authorizers contract
    AuthorizersAddress: 0xFE20Ce9fBe514397427d20C91CB657a4478A0FFa
    # Address of WZCN token (Example: https://ropsten.etherscan.io/token/0x930E1BE76461587969Cb7eB9BFe61166b1E70244)
    WzcnAddress: 0x930E1BE76461587969Cb7eB9BFe61166b1E70244
    # URL of ethereum RPC node (infura or alchemy)
    EthereumNodeURL: https://ropsten.infura.io/v3/22cb2849f5f74b8599f3dc2a23085bd4
    # Gas limit to execute ethereum transaction
    GasLimit: 300000
    # Value to execute ZCN smart contracts in wei
    Value: 0
```

```yaml
# bridge client config
bridge:
    # KeyStorage unlock storage
    Password: password
    # User's Ethereum address (should be registered in the local key storage)
    EthereumAddress: 0x860FA46F170a87dF44D7bB867AA4a5D2813127c1
    # Address of Ethereum bridge contract
    BridgeAddress: 0xF26B52df8c6D9b9C20bfD7819Bed75a75258c7dB
    # Address of WZCN token (Example: https://ropsten.etherscan.io/token/0x930E1BE76461587969Cb7eB9BFe61166b1E70244)
    WzcnAddress: 0x930E1BE76461587969Cb7eB9BFe61166b1E70244
    # URL of ethereum RPC node (infura or alchemy)
    EthereumNodeURL: https://ropsten.infura.io/v3/22cb2849f5f74b8599f3dc2a23085bd4
    # Gas limit to execute ethereum transaction
    GasLimit: 300000
    # Value to execute ZCN smart contracts in wei
    Value: 0
    ConsensusThreshold: 70.0
```

## Here is the default prerequisites content

Tasks to complete before merging PR:
- [ ]  Ensure system tests are passing. If not [Run them manually](https://github.com/0chain/blobber/actions/workflows/system_tests.yml) to check for any regressions :clipboard:
- [ ]  Do any new system tests need added to test this change? do any existing system tests need updated? If so create a PR at [0chain/system_test](https://github.com/0chain/system_test)
- [ ]  Merge your system tests PR to master BEFORE merging this PR

Associated PRs (Link as appropriate):
...

### CODE REVIEW

**Comment by service-0chain** [comment]
Manual system tests [failure] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | FALSE  |
| system-tests  | feature/default_client_config  |
| gosdk  | feature/default_client_config  |
| zboxcli  | staging  |
| zwalletcli  | feature/update_74  |
| 0chain  | feature/zcnsc_eventsdb_storage  |
| blobber  | staging  |
| 0box  | staging  |
| 0block  | staging  |
| 0dns  | staging  |
| explorer  | staging  |
| 0proxy  | staging  |
| 0search  | staging  |

**Comment by service-0chain** [comment]
Manual system tests [failure] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | FALSE  |
| system-tests  | feature/zcnsc_zwallet_update_74  |
| gosdk  | feature/default_client_config  |
| zboxcli  | staging  |
| zwalletcli  | feature/update_74  |
| 0chain  | staging  |
| blobber  | staging  |
| authorizer  | staging  |
| 0box  | staging  |
| 0block  | staging  |
| 0dns  | staging  |
| explorer  | staging  |
| 0proxy  | staging  |
| 0search  | staging  |

**Comment by service-0chain** [comment]
Manual system tests [success] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | FALSE  |
| system-tests  | feature/zcnsc_zwallet_update_74  |
| gosdk  | feature/default_client_config  |
| zboxcli  | staging  |
| zwalletcli  | feature/update_74  |
| 0chain  | staging  |
| blobber  | staging  |
| authorizer  | staging  |
| 0box  | staging  |
| 0block  | staging  |
| 0dns  | staging  |
| explorer  | staging  |
| 0proxy  | staging  |
| 0search  | staging  |

**Review by stewartie4 — APPROVED** [review]
approving on behalf of @cnlangzi / @Sriep as per https://0chain.slack.com/archives/C02AV6MKT36/p1644104715711039?thread_ts=1644101141.278579&cid=C02AV6MKT36

**Pull request merged**
