### PR TITLE
fix(upload):break upload if any error is thrown from blobber

### LINKED ISSUE #130: Stop unwanted requests if the initial validation is not passed.
For example in the case of re-uploading an already existing file via CLI I can see that multiple chunk requests are hit on the server but instead we can minimize the overload and cost by not hitting the requests in the first place if its already existing or similar validation is failed in other cases too.
Screen Shot 2021-11-21 at 21 45 24

### LINKED ISSUE #266: [FEATURE] [chunkupload]stop to commit, and show detail error if upload fails

### PR DESCRIPTION
**Pull request by cnlangzi**
### Changes
-

### Fixes
- fixed: https://github.com/0chain/gosdk/issues/266
- fixed: https://github.com/0chain/zboxcli/issues/130

### Tests
Tasks to complete before merging PR:
- [ ]  Ensure system tests are passing. If not [Run them manually](https://github.com/0chain/gosdk/actions/workflows/system_tests.yml) to check for any regressions :clipboard:
- [ ]  Do any new system tests need added to test this change? do any existing system tests need updated? If so create a PR at [0chain/system_test](https://github.com/0chain/system_test)
- [ ]  Merge your system tests PR to master AFTER merging this PR

### Associated PRs (Link as appropriate):
- zboxcli: https://github.com/0chain/zboxcli/pull/193
- system_test: https://github.com/0chain/system_test/pull/213

### CODE REVIEW

**Review by peterlimg — APPROVED** [review]
lgtm

**Comment by service-0chain** [comment]
Manual system tests [failure] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | FALSE  |
| system-tests  | fix/break_upload_on_error  |
| gosdk  | fix/break_upload_on_error  |
| zboxcli  | fix/break_upload_on_error  |
| zwalletcli  | staging  |
| 0chain  | staging  |
| blobber  | staging  |
| authorizer  | staging  |
| 0box  | staging  |
| 0block  | staging  |
| 0dns  | staging  |
| explorer  | staging  |
| 0proxy  | staging  |
| 0search  | staging  |

**Comment by service-0chain** [comment]
Manual system tests [success] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | FALSE  |
| system-tests  | fix/break_upload_on_error  |
| gosdk  | fix/break_upload_on_error  |
| zboxcli  | fix/break_upload_on_error  |
| zwalletcli  | staging  |
| 0chain  | staging  |
| blobber  | staging  |
| authorizer  | staging  |
| 0box  | staging  |
| 0block  | staging  |
| 0dns  | staging  |
| explorer  | staging  |
| 0proxy  | staging  |
| 0search  | staging  |

**Comment by service-0chain** [comment]
Manual system tests [failure] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | FALSE  |
| system-tests  | master  |
| gosdk  | staging  |
| zboxcli  | new_alloc  |
| zwalletcli  | staging  |
| 0chain  | alloc_blobber  |
| blobber  | staging  |
| authorizer  | staging  |
| 0box  | staging  |
| 0block  | staging  |
| 0dns  | staging  |
| explorer  | staging  |
| 0proxy  | staging  |
| 0search  | staging  |

**Comment by service-0chain** [comment]
Manual system tests [success] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | FALSE  |
| system-tests  | master  |
| gosdk  | staging  |
| zboxcli  | new_alloc  |
| zwalletcli  | staging  |
| 0chain  | alloc_blob  |
| blobber  | staging  |
| authorizer  | staging  |
| 0box  | staging  |
| 0block  | staging  |
| 0dns  | staging  |
| explorer  | staging  |
| 0proxy  | staging  |
| 0search  | staging  |

**Comment by service-0chain** [comment]
Manual system tests [success] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | FALSE  |
| system-tests  | master  |
| gosdk  | staging  |
| zboxcli  | staging  |
| zwalletcli  | staging  |
| 0chain  | staging  |
| blobber  | staging  |
| authorizer  | staging  |
| 0box  | staging  |
| 0block  | staging  |
| 0dns  | staging  |
| explorer  | staging  |
| 0proxy  | staging  |
| 0search  | staging  |

**Pull request merged**
