### PR TITLE
feat(zcncore): added CryptoJsEncrypt and CryptoJsDecrypt

### PR DESCRIPTION
**Pull request by cnlangzi**
### Changes
- added zcncore.CryptoJsEcnrypt and CryptoJsDecrypt. they can work with crypto-js library

### Fixes
- added unit tests for zcncore/Encrypt and zcncore/Decrypt

### Tests
Tasks to complete before merging PR:
- [ ]  Ensure system tests are passing. If not [Run them manually](https://github.com/0chain/gosdk/actions/workflows/system_tests.yml) to check for any regressions :clipboard:
- [ ]  Do any new system tests need added to test this change? do any existing system tests need updated? If so create a PR at [0chain/system_test](https://github.com/0chain/system_test)
- [ ]  Merge your system tests PR to master AFTER merging this PR

### Associated PRs (Link as appropriate):
-

### CODE REVIEW

**Review by peterlimg — DISMISSED** [review]
We need to use scrypt to do the wallet encryption to reduce the possibility for brute force attack. And we need to chose different difficult levels for different devices, mainly for mobile device and computers.

**Comment by cnlangzi** [comment]
> We need to use scrypt to do the wallet encryption to reduce the possibility for brute force attack. And we need to chose different difficult levels for different devices, mainly for mobile device and computers.

@peterlimg  could you share an example or library? AES+ccb+pkcs5 is used on all web-apps to encrypt mnemonics. if it is not good, we need update all of them.

**Review by dabasov — APPROVED** [review]
merge if only this discussion resolved https://0chain.slack.com/archives/C028ZCJT6LU/p1671819371357019?thread_ts=1670934075.106909&cid=C028ZCJT6LU

**Comment by service-0chain** [comment]
Manual system tests [failure] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | FALSE  |
| system-tests  | 398-new-system-test-for-nft-allocation-features  |
| gosdk  | staging  |
| zboxcli  | 149-nft-changes  |
| zwalletcli  | staging  |
| 0chain  | 828-nft-restrict-file-access-options  |
| blobber  | 476-toggle-permission-to-uploaddelete-update-move-copy-and-rename  |
| authorizer  | staging  |
| 0box  | staging  |
| 0block  | staging  |
| 0dns  | staging  |
| explorer  | staging  |
| 0proxy  | staging  |
| 0search  | staging  |

**Comment by service-0chain** [comment]
Manual system tests [failure] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | FALSE  |
| system-tests  | master  |
| gosdk  | staging  |
| zboxcli  | staging  |
| zwalletcli  | staging  |
| 0chain  | staging  |
| blobber  | staging  |
| authorizer  | staging  |
| 0box  | staging  |
| 0block  | staging  |
| 0dns  | staging  |
| explorer  | staging  |
| 0proxy  | staging  |
| 0search  | staging  |

**Pull request merged**
