### PR TITLE
Fix web streaming - wasm

### PR DESCRIPTION
**Pull request by peterlimg**
### Changes
- Add DownloadBlocks to allocation to use the same download methods as DownloadFileByBlocks, the difference is it accept opened file of `sys.File` type which is used in wasm to open memfile. 

### Fixes
- 

### Tests
Tasks to complete before merging PR:
- [ ]  Ensure system tests are passing. If not [Run them manually](https://github.com/0chain/gosdk/actions/workflows/system_tests.yml) to check for any regressions :clipboard:
- [ ]  Do any new system tests need added to test this change? do any existing system tests need updated? If so create a PR at [0chain/system_test](https://github.com/0chain/system_test)
- [ ]  Merge your system tests PR to master AFTER merging this PR

### Associated PRs (Link as appropriate):
- blobber:
- 0chain:
- system_test:
- zboxcli:
- zwalletcli:
- Other: ...

### CODE REVIEW

**Review by cnlangzi — APPROVED** [review]

**Comment by Hitenjain14** [comment]
Hi @peterlimg is there any need for DownloadBlocks when we have [DownloadByBlocksToFileHandler](https://github.com/0chain/gosdk/blob/staging/zboxcore/sdk/allocation.go#L963)

**Comment by peterlimg** [comment]
Hi @Hitenjain14 DownloadByBlocksToFileHandler does not work in wasm, we can't use `os` package to operate the files in wasm

**Comment by Hitenjain14** [comment]
> Hi @Hitenjain14 DownloadByBlocksToFileHandler does not work in wasm, we can't use `os` package to operate the files in wasm

Where are we using os package in that method we take `sys.FIle` in input and seems like the parameters are same too.

**Comment by peterlimg** [comment]
oh, I thought you mean the `downloadFileByBlocks`. Didn't know we have that method before, just add what I needed. Let me replace the downloadBlocks.

**Pull request merged**
