### PR TITLE
feat(commit): removed commit

### LINKED ISSUE #447: Remove commit feature, commitMetaTxn and related code
Re should remove the commit feature and related code.
For example remove
- [CommitMetaTransaction](https://github.com/0chain/gosdk/blob/staging/zboxcore/sdk/allocation.go#L1281)
- [zboxcli.commit.go](https://github.com/0chain/zboxcli/blob/staging/cmd/commit.go)
- [commitMetaTxn](https://github.com/0chain/zboxcli/blob/staging/cmd/common.go#L107) in zbox
- Plus any linked code

### PR DESCRIPTION
**Pull request by cnlangzi**
### Changes
- removed `commit`: https://github.com/0chain/gosdk/issues/447

### Fixes
- 

### Tests
Tasks to complete before merging PR:
- [ ]  Ensure system tests are passing. If not [Run them manually](https://github.com/0chain/gosdk/actions/workflows/system_tests.yml) to check for any regressions :clipboard:
- [ ]  Do any new system tests need added to test this change? do any existing system tests need updated? If so create a PR at [0chain/system_test](https://github.com/0chain/system_test)
- [ ]  Merge your system tests PR to master AFTER merging this PR

### Associated PRs (Link as appropriate):
- zboxcli: https://github.com/0chain/zboxcli/pull/302
- system_test: https://github.com/0chain/system_test/pull/427

### CODE REVIEW

**Comment by service-0chain** [comment]
Manual system tests [cancelled] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | FALSE  |
| system-tests  | master  |
| gosdk  | fix/remove_commit  |
| zboxcli  | fix/remove_commit  |
| zwalletcli  | staging  |
| 0chain  | staging  |
| blobber  | staging  |
| authorizer  | staging  |
| 0box  | staging  |
| 0block  | staging  |
| 0dns  | staging  |
| explorer  | staging  |
| 0proxy  | staging  |
| 0search  | staging  |

**Comment by service-0chain** [comment]
Manual system tests [cancelled] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | FALSE  |
| system-tests  | fix/remove_commit  |
| gosdk  | fix/remove_commit  |
| zboxcli  | fix/remove_commit  |
| zwalletcli  | staging  |
| 0chain  | staging  |
| blobber  | staging  |
| authorizer  | staging  |
| 0box  | staging  |
| 0block  | staging  |
| 0dns  | staging  |
| explorer  | staging  |
| 0proxy  | staging  |
| 0search  | staging  |

**Comment by service-0chain** [comment]
Manual system tests [failure] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | FALSE  |
| system-tests  | fix/remove_commit  |
| gosdk  | fix/remove_commit  |
| zboxcli  | fix/remove_commit  |
| zwalletcli  | staging  |
| 0chain  | staging  |
| blobber  | staging  |
| authorizer  | staging  |
| 0box  | staging  |
| 0block  | staging  |
| 0dns  | staging  |
| explorer  | staging  |
| 0proxy  | staging  |
| 0search  | staging  |

**Review by peterlimg — APPROVED** [review]
lgtm

**Comment by service-0chain** [comment]
Manual system tests [success] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | FALSE  |
| system-tests  | fix/remove_commit  |
| gosdk  | fix/remove_commit  |
| zboxcli  | fix/remove_commit  |
| zwalletcli  | staging  |
| 0chain  | staging  |
| blobber  | staging  |
| authorizer  | staging  |
| 0box  | staging  |
| 0block  | staging  |
| 0dns  | staging  |
| explorer  | staging  |
| 0proxy  | staging  |
| 0search  | staging  |

**Pull request merged**
