### PR TITLE
Wrapper for kill_miner and kill_sharder

### PR DESCRIPTION
**Pull request by Sriep**
### Changes
-

### Fixes
-

### Tests
Tasks to complete before merging PR:
- [ ]  Ensure system tests are passing. If not [Run them manually](https://github.com/0chain/gosdk/actions/workflows/system_tests.yml) to check for any regressions :clipboard:
- [ ]  Do any new system tests need added to test this change? do any existing system tests need updated? If so create a PR at [0chain/system_test](https://github.com/0chain/system_test)
- [ ]  Merge your system tests PR to master AFTER merging this PR

### Associated PRs (Link as appropriate):
- blobber:
- 0chain: https://github.com/0chain/0chain/pull/2285
- system_test: https://github.com/0chain/system_test/pull/631
- zboxcli:
- zwalletcli: https://github.com/0chain/zwalletcli/pull/154
- Other: ...

### CODE REVIEW

**Comment by service-0chain** [comment]
Manual system tests [failure] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | FALSE  |
| system-tests  | kill_miner  |
| gosdk  | minersc_kill  |
| zboxcli  | staging  |
| zwalletcli  | kill_miners  |
| 0chain  | kill_minersc  |
| blobber  | staging  |
| authorizer  | staging  |
| 0box  | staging  |
| 0dns  | staging  |

**Comment by service-0chain** [comment]
Manual system tests [failure] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | FALSE  |
| system-tests  | kill_miner  |
| gosdk  | minersc_kill  |
| zboxcli  | staging  |
| zwalletcli  | kill_miners  |
| 0chain  | pr-2285-0e9c3888  |
| blobber  | staging  |
| authorizer  | staging  |
| 0box  | staging  |
| 0dns  | staging  |

**Comment by service-0chain** [comment]
Manual system tests [failure] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | FALSE  |
| system-tests  | kill_miner  |
| gosdk  | minersc_kill  |
| zboxcli  | kill_miners  |
| zwalletcli  | staging  |
| 0chain  | kill_minersc  |
| blobber  | staging  |
| authorizer  | staging  |
| 0box  | staging  |
| 0dns  | staging  |

**Review by peterlimg — APPROVED** [review]
LGTM

**Pull request merged**
