### PR TITLE
Updating blobber and validator update setting models.

### PR DESCRIPTION
**Pull request by sunilmhta**
### Fixes
https://github.com/0chain/0chain/issues/2544

### Tests
Tasks to complete before merging PR:
- [ ]  Ensure system tests are passing. If not [Run them manually](https://github.com/0chain/gosdk/actions/workflows/system_tests.yml) to check for any regressions :clipboard:
- [ ]  Do any new system tests need added to test this change? do any existing system tests need updated? If so create a PR at [0chain/system_test](https://github.com/0chain/system_test)
- [ ]  Merge your system tests PR to master AFTER merging this PR

### Associated PRs (Link as appropriate):
- blobber:
- gosdk: https://github.com/0chain/gosdk/pull/1095
- system_test:
- zboxcli: https://github.com/0chain/zboxcli/pull/480
- zwalletcli: 
- 0chain: https://github.com/0chain/0chain/pull/2596

### CODE REVIEW

**Comment by service-0chain** [comment]
Manual system tests [failure] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | false  |
| system-tests  | sprint-july-1  |
| gosdk  | users/sunilmhta/fix/2544/updateblobnvalidator  |
| zboxcli  | users/sunilmhta/fix/2544/updateblobnvalidator  |
| zwalletcli  | sprint-july-1  |
| 0chain  | sprint-july-1  |
| blobber  | sprint-july-1  |
| authorizer  | staging  |
| 0box  | staging  |
| 0dns  | staging  |

**Comment by service-0chain** [comment]
Manual system tests [failure] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | false  |
| system-tests  | sprint-july-1  |
| gosdk  | users/sunilmhta/fix/2544/updateblobnvalidator  |
| zboxcli  | users/sunilmhta/fix/2544/updateblobnvalidator  |
| zwalletcli  | sprint-july-1  |
| 0chain  | users/sunilmhta/fix/2544/0chain/blobber-settings  |
| blobber  | sprint-july-1  |
| authorizer  | sprint-july-1  |
| 0box  | sprint-july-1  |
| 0dns  | staging  |

**Comment by service-0chain** [comment]
Manual system tests [failure] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | false  |
| system-tests  | sprint-july-1  |
| gosdk  | users/sunilmhta/fix/2544/updateblobnvalidator  |
| zboxcli  | users/sunilmhta/fix/2544/updateblobnvalidator  |
| zwalletcli  | sprint-july-1  |
| 0chain  | users/sunilmhta/fix/2544/0chain/blobber-settings  |
| blobber  | sprint-july-1  |
| authorizer  | staging  |
| 0box  | staging  |
| 0dns  | staging  |

**Comment by service-0chain** [comment]
Manual system tests [failure] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | false  |
| system-tests  | sprint-july-1  |
| gosdk  | users/sunilmhta/fix/2544/updateblobnvalidator  |
| zboxcli  | users/sunilmhta/fix/2544/updateblobnvalidator  |
| zwalletcli  | staging  |
| 0chain  | users/sunilmhta/fix/2544/0chain/blobber-settings  |
| blobber  | sprint-july-1  |
| authorizer  | staging  |
| 0box  | staging  |
| 0dns  | staging  |

**Comment by service-0chain** [comment]
Manual system tests [failure] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | false  |
| system-tests  | sprint-july-1  |
| gosdk  | users/sunilmhta/fix/2544/updateblobnvalidator  |
| zboxcli  | users/sunilmhta/fix/2544/updateblobnvalidator  |
| zwalletcli  | sprint-july-1  |
| 0chain  | users/sunilmhta/fix/2544/0chain/blobber-settings  |
| blobber  | sprint-july-1  |
| authorizer  | sprint-july-1  |
| 0box  | staging  |
| 0dns  | staging  |

**Comment by service-0chain** [comment]
Manual system tests [failure] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | false  |
| system-tests  | sprint-july-1  |
| gosdk  | users/sunilmhta/fix/2544/updateblobnvalidator  |
| zboxcli  | users/sunilmhta/fix/2544/updateblobnvalidato  |
| zwalletcli  | sprint-july-1  |
| 0chain  | users/sunilmhta/fix/2544/0chain/blobber-settings  |
| blobber  | staging  |
| authorizer  | staging  |
| 0box  | staging  |
| 0dns  | staging  |

**Comment by service-0chain** [comment]
Manual system tests [failure] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | false  |
| system-tests  | sprint-july-1  |
| gosdk  | users/sunilmhta/fix/2544/updateblobnvalidator  |
| zboxcli  | users/sunilmhta/fix/2544/updateblobnvalidator  |
| zwalletcli  | sprint-july-1  |
| 0chain  | users/sunilmhta/fix/2544/0chain/blobber-settings  |
| blobber  | staging  |
| authorizer  | staging  |
| 0box  | staging  |
| 0dns  | staging  |

**Review by dabasov — APPROVED** [review]
lgtm

**Pull request merged**
