### PR TITLE
fix(upload): encrypt thumbnail bytes

### LINKED ISSUE #374: error when trying to download thumbnail for encrypted file
```
alloc=$(zbox newallocation --lock 1 --data 1 --parity 1 --silent | awk -F: '{print $NF}' | xargs)
zbox upload --allocation $alloc --localpath ./go.sum --remotepath /go6.sum --thumbnailpath ./go.sum --encrypt
zbox download --localpath ./ --allocation $alloc --thumbnail --remotepath /go6.sum
```

results in error:
```
 per blobber: 131072
 0 / 66308 [-----------------------------------------------------------------------------------------------------------------------------------------]   0.00%0box-sdk        [INFO]   2023/03/05 08:35:40.606858 downloadworker.go:404: Downloading block 1 - 2
0box-sdk        [INFO]   2023/03/05 08:35:40.644975 blockdownloadworker.go:186: Will be retrying download
0box-sdk        [INFO]   2023/03/05 08:35:40.644975 blockdownloadworker.go:186: Will be retrying download
0box-sdk        [DEBUG]  2023/03/05 08:35:40.645126 blockdownloadworker.go:236: Retrying for Error occurred: stale_read_marker: readmarker counter is not in sync with latest counter
0box-sdk        [DEBUG]  2023/03/05 08:35:40.645191 blockdownloadworker.go:236: Retrying for Error occurred: stale_read_marker: readmarker counter is not in sync with latest counter
0box-sdk        [ERROR]  2023/03/05 08:35:40.752998 downloadworker.go:277: Block decryption failedhttp://100.78.70.98:5054Invalid Ciphertext in decrypt, C4 != H5
0box-sdk        [ERROR]  2023/03/05 08:35:40.753090 downloadworker.go:198: decryption_error: Decryption error Invalid Ciphertext in decrypt, C4 != H5 while decrypting data from http://100.78.70.98:5054 blobber
0box-sdk        [ERROR]  2023/03/05 08:35:40.772458 downloadworker.go:277: Block decryption failedhttp://100.78.70.98:5055Invalid Ciphertext in decrypt, C4 != H5
0box-sdk        [ERROR]  2023/03/05 08:35:40.772588 downloadworker.go:198: decryption_error: Decryption error Invalid Ciphertext in decrypt, C4 != H5 while decrypting data from http://100.78.70.98:5055 blobber
 0 / 66308 [--------------------------------------------------------------------------------------------------------------------------------------]   0.00% 0s
Error in file operation: Download failed for block 1.
download_failed: 2 failed blobbers exceeded 1 remaining blobbers. Download errors: Error decryption_error: Decryption error Invalid Ciphertext in decrypt, C4 != H5 while decrypting data from http://100.78.70.98:5054 blobber from http://100.78.70.98:5054 Error decryption_error: Decryption error Invalid Ciphertext in decrypt, C4 != H5 while decrypting data from http://100.78.70.98:5055 blobber from http://100.78.70.98:5055
```

tasks:
- [ ] fix issue
- [ ] add system_tests

### PR DESCRIPTION
**Pull request by cnlangzi**
### Changes
-

### Fixes
- fixed https://github.com/0chain/zboxcli/issues/374

### Tests
Tasks to complete before merging PR:
- [ ]  Ensure system tests are passing. If not [Run them manually](https://github.com/0chain/gosdk/actions/workflows/system_tests.yml) to check for any regressions :clipboard:
- [ ]  Do any new system tests need added to test this change? do any existing system tests need updated? If so create a PR at [0chain/system_test](https://github.com/0chain/system_test)
- [ ]  Merge your system tests PR to master AFTER merging this PR

### Associated PRs (Link as appropriate):
- gosdk: https://github.com/0chain/gosdk/pull/848
- zboxcli: https://github.com/0chain/zboxcli/pull/386
- system_test: https://github.com/0chain/system_test/pull/585

### CODE REVIEW

**Comment by service-0chain** [comment]
Manual system tests [success] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | ABILITY TO SKIP TESTS IS DISABLED. SKIP_TESTS OPTION IGNORED.  |
| system-tests  | fix/encrypt_thumbnail  |
| gosdk  | fix/encrypt_thumbnail  |
| zboxcli  | fix/encrypt_thumbnail  |
| zwalletcli  | staging  |
| 0chain  | staging  |
| blobber  | staging  |
| authorizer  | staging  |
| 0box  | staging  |
| 0block  | staging  |
| 0dns  | staging  |
| explorer  | staging  |
| 0proxy  | staging  |
| 0search  | staging  |

**Review by peterlimg — APPROVED** [review]
LGTM

**Comment by service-0chain** [comment]
Manual system tests [failure] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | FALSE  |
| system-tests  | fix/encrypt_thumbnail  |
| gosdk  | fix/encrypt_thumbnail  |
| zboxcli  | fix/encrypt_thumbnail  |
| zwalletcli  | staging  |
| 0chain  | staging  |
| blobber  | staging  |
| authorizer  | staging  |
| 0box  | staging  |
| 0block  | staging  |
| 0dns  | staging  |
| explorer  | staging  |
| 0proxy  | staging  |
| 0search  | staging  |

**Comment by service-0chain** [comment]
Manual system tests [success] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | FALSE  |
| system-tests  | fix/encrypt_thumbnail  |
| gosdk  | fix/encrypt_thumbnail  |
| zboxcli  | fix/encrypt_thumbnail  |
| zwalletcli  | staging  |
| 0chain  | staging  |
| blobber  | staging  |
| authorizer  | staging  |
| 0box  | staging  |
| 0block  | staging  |
| 0dns  | staging  |
| explorer  | staging  |
| 0proxy  | staging  |
| 0search  | staging  |

**Pull request merged**
