### PR TITLE
Change the contract of Sharder and Miner update settings

### PR DESCRIPTION
**Pull request by sunilmhta**
### Changes
-

### Fixes
https://github.com/0chain/0chain/issues/2544

### Tests
Tasks to complete before merging PR:
- [ ]  Ensure system tests are passing. If not [Run them manually](https://github.com/0chain/gosdk/actions/workflows/system_tests.yml) to check for any regressions :clipboard:
- [ ]  Do any new system tests need added to test this change? do any existing system tests need updated? If so create a PR at [0chain/system_test](https://github.com/0chain/system_test)
- [ ]  Merge your system tests PR to master AFTER merging this PR

### Associated PRs (Link as appropriate):
- blobber:
- 0chain: https://github.com/0chain/0chain/pull/2577
- system_test:
- zboxcli:
- zwalletcli: https://github.com/0chain/zwalletcli/pull/274
- Other: ...

### CODE REVIEW

**Review by dabasov — APPROVED** [review]
lgtm

**Comment by service-0chain** [comment]
Manual system tests [failure] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | false  |
| system-tests  | master  |
| gosdk  | users/sunilmhta/fix/2544/gosdk-sharder-miner  |
| zboxcli  | sprint-july-1  |
| zwalletcli  | users/sunilmhta/fix/2544/zwallet-sharder-miner  |
| 0chain  | users/sunilmhta/fix/2544/0chain/usingmap  |
| blobber  | sprint-july-1  |
| authorizer  | sprint-july-1  |
| 0box  | sprint-july-1  |
| 0dns  | staging  |

**Comment by service-0chain** [comment]
Manual system tests [failure] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | false  |
| system-tests  | master  |
| gosdk  | users/sunilmhta/fix/2544/gosdk-sharder-miner  |
| zboxcli  | sprint-july-1  |
| zwalletcli  | users/sunilmhta/fix/2544/zwallet-sharder-miner  |
| 0chain  | users/sunilmhta/fix/2544/0chain/usingmap  |
| blobber  | staging  |
| authorizer  | staging  |
| 0box  | staging  |
| 0dns  | staging  |

**Comment by service-0chain** [comment]
Manual system tests [failure] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | false  |
| system-tests  | sprint-july-1  |
| gosdk  | users/sunilmhta/fix/2544/gosdk-sharder-miner  |
| zboxcli  | sprint-july-1  |
| zwalletcli  | users/sunilmhta/fix/2544/zwallet-sharder-miner  |
| 0chain  | users/sunilmhta/fix/2544/0chain/usingmap  |
| blobber  | staging  |
| authorizer  | staging  |
| 0box  | staging  |
| 0dns  | staging  |

**Comment by service-0chain** [comment]
Manual system tests [cancelled] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | false  |
| system-tests  | master  |
| gosdk  | users/sunilmhta/fix/2544/gosdk-sharder-miner  |
| zboxcli  | staging  |
| zwalletcli  | users/sunilmhta/fix/2544/zwallet-sharder-miner  |
| 0chain  | users/sunilmhta/fix/2544/0chain/usingmap  |
| blobber  | staging  |
| authorizer  | staging  |
| 0box  | staging  |
| 0dns  | staging  |

**Comment by service-0chain** [comment]
Manual system tests [failure] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | false  |
| system-tests  | sprint-july-1  |
| gosdk  | sprint-july-1  |
| zboxcli  | sprint-july-1  |
| zwalletcli  | sprint-july-1  |
| 0chain  | max_charge  |
| blobber  | staging  |
| authorizer  | staging  |
| 0box  | staging  |
| 0dns  | staging  |

**Comment by service-0chain** [comment]
Manual system tests [cancelled] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | false  |
| system-tests  | sprint-july-1  |
| gosdk  | users/sunilmhta/fix/2544/gosdk-sharder-miner  |
| zboxcli  | staging  |
| zwalletcli  | users/sunilmhta/fix/2544/zwallet-sharder-miner  |
| 0chain  | users/sunilmhta/fix/2544/0chain/usingmap  |
| blobber  | staging  |
| authorizer  | staging  |
| 0box  | staging  |
| 0dns  | staging  |

**Comment by service-0chain** [comment]
Manual system tests [success] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | false  |
| system-tests  | sprint-july-1  |
| gosdk  | users/sunilmhta/fix/2544/gosdk-sharder-miner  |
| zboxcli  | sprint-july-1  |
| zwalletcli  | users/sunilmhta/fix/2544/zwallet-sharder-miner  |
| 0chain  | users/sunilmhta/fix/2544/0chain/usingmap  |
| blobber  | staging  |
| authorizer  | staging  |
| 0box  | staging  |
| 0dns  | staging  |

**Pull request merged**
