### PR TITLE
Fix resumed upload

### LINKED ISSUE #1192: bug: the latest `MerkleRoot` or `WriteMarker` of parent folder should be added in progress id
## reproduce `empty actual file hash field` bug
- upload file1.png,
- upload file1.png again, it will be rejected by `duplicated_file` error
- delete file1.png
- upload file1.png. it will throw `empty actual file hash field` error. because the progress file is not deleted from ~/.zcn. it will be consider as resume instead of upload. actually it is deleted. 

## discussion 
- https://0chain.slack.com/archives/G01EXH6EYC9/p1693186258565699

## solutions
- the latest `MerkleRoot` or `WriteMarker` of parent folder should be added in progress id. the upload file1.png after deleting, it will get a new progress id. because of `MerkleRoot` or `WriteMarker` of its parent folder has been changed.
-  delete progress file if error is not 5xx or network issue from blobber

### PR DESCRIPTION
**Pull request by din-mukhammed**
### Changes
-

### Fixes
- Fixed upload progress cleanup
- Fixed connectionID reuse for resumed uploads

### Tests
Tasks to complete before merging PR:
- [ ]  Ensure system tests are passing. If not [Run them manually](https://github.com/0chain/gosdk/actions/workflows/system_tests.yml) to check for any regressions :clipboard:
- [ ]  Do any new system tests need added to test this change? do any existing system tests need updated? If so create a PR at [0chain/system_test](https://github.com/0chain/system_test)
- [ ]  Merge your system tests PR to master AFTER merging this PR

### Associated PRs (Link as appropriate):
- blobber:
- 0chain:
- system_test:
- zboxcli:
- zwalletcli:
- Other: ...

### CODE REVIEW

**Comment by service-0chain** [comment]
Manual system tests [cancelled] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | false  |
| system-tests  |   |
| gosdk  | fix/upload-progress  |
| zboxcli  |   |
| zwalletcli  |   |
| 0chain  |   |
| blobber  |   |
| authorizer  |   |
| 0box  |   |
| 0dns  |   |

**Comment by service-0chain** [comment]
Manual system tests [failure] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | false  |
| system-tests  |   |
| gosdk  | fix/upload-progress  |
| zboxcli  |   |
| zwalletcli  |   |
| 0chain  |   |
| blobber  |   |
| authorizer  |   |
| 0box  |   |
| 0dns  |   |

**Review by Hitenjain14 — APPROVED** [review]
lgtm

**Review by dabasov — APPROVED** [review]
lgtm

**Pull request merged**
