### PR TITLE
Corrected size and actual file size for get file meta

### LINKED ISSUE #399: sdk.ListDir() returns actual_size as 0 for directories
```
➜  zbox list --allocation $alloc --remotepath / --silent
  TYPE | NAME | PATH  | SIZE | ACTUAL SIZE | NUM BLOCKS |                           LOOKUP HASH                            | IS ENCRYPTED
-------+------+-------+------+-------------+------------+------------------------------------------------------------------+---------------
  d    | test | /test |      |           0 |          4 | 687a78a4917c1f0a48abd29d198fe26851f8f60c6f895c6f60fa292f54944dd2 |
```

but the folder actually have some files in it. 

```
✗ zbox list --allocation $alloc --remotepath /test --silent
  TYPE |  NAME   |     PATH      |  SIZE  | ACTUAL SIZE | NUM BLOCKS |                           LOOKUP HASH                            | IS ENCRYPTED
-------+---------+---------------+--------+-------------+------------+------------------------------------------------------------------+---------------
  f    | go5.sum | /test/go5.sum | 131912 |       65956 |          4 | 40469df2b64f3d15c6e8a41652cb758e968d7a5fdd6c73d6c2c90ca648276856 | NO
```

### PR DESCRIPTION
**Pull request by pgrudra**
### Changes
corrected Size and ActualFileSize in GetFileMeta

### Tests
Tasks to complete before merging PR:
- [ ]  Ensure system tests are passing. If not [Run them manually](https://github.com/0chain/gosdk/actions/workflows/system_tests.yml) to check for any regressions :clipboard:
- [ ]  Do any new system tests need added to test this change? do any existing system tests need updated? If so create a PR at [0chain/system_test](https://github.com/0chain/system_test)
- [ ]  Merge your system tests PR to master AFTER merging this PR

### Associated PRs (Link as appropriate):
- blobber:
- 0chain:
- system_test: https://github.com/0chain/system_test/pull/615
- zboxcli:
- zwalletcli:
- Other: ...

### CODE REVIEW

**Review by cnlangzi — APPROVED** [review]
LGTM

**Comment by cnlangzi** [comment]
@pgrudra  please also fix system_tests. cc @Kishan-Dhakan

**Comment by service-0chain** [comment]
Manual system tests [failure] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | FALSE  |
| system-tests  | corrections_for_gosdk_pr_3192  |
| gosdk  | corrected_size_and_actual_file_size_for_get_file_meta  |
| zboxcli  | staging  |
| zwalletcli  | staging  |
| 0chain  | staging  |
| blobber  | staging  |
| authorizer  | staging  |
| 0box  | staging  |
| 0block  | staging  |
| 0dns  | staging  |
| explorer  | staging  |
| 0proxy  | staging  |
| 0search  | staging  |

**Comment by service-0chain** [comment]
Manual system tests [success] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | FALSE  |
| system-tests  | corrections_for_gosdk_pr_3192  |
| gosdk  | corrected_size_and_actual_file_size_for_get_file_meta  |
| zboxcli  | staging  |
| zwalletcli  | staging  |
| 0chain  | staging  |
| blobber  | staging  |
| authorizer  | staging  |
| 0box  | staging  |
| 0block  | staging  |
| 0dns  | staging  |
| explorer  | staging  |
| 0proxy  | staging  |
| 0search  | staging  |

**Comment by Kishan-Dhakan** [comment]
@peterlimg this is not ready to merge, the changes do not make much sense from client perspective. Please see https://0chain.slack.com/archives/C02AV6MKT36/p1680467150255849. I'm reverting it.

**Pull request merged**
