### PR TITLE
changed data type of staked to common.TimeStamp

### LINKED ISSUE #727: `staked_at` is incorrect in ./zbox sp-user-info
```
./zbox sp-user-info                                               03:12:07
0chain-core-sdk [INFO]   2023/01/18 03:12:12.978782 wallet_base.go:285: ******* Wallet SDK Version:v1.8.9-57-g7fbdcff ******* (SetLogFile)
0box-sdk        [INFO]   2023/01/18 03:12:12.978953 sdk.go:74: ******* Storage SDK Version: v1.8.9-57-g7fbdcff *******
0chain-core-sdk [INFO]   2023/01/18 03:12:13.981579 transaction_base.go:136: ******* Wallet SDK Version:v1.8.9-57-g7fbdcff ******* (InitZCNSDK)
0box-sdk        [DEBUG]  2023/01/18 03:12:14.953747 networkworker.go:105: Get network result:{"miners":["https://dev.0chain.net/miner03","https://dev.0chain.net/miner02","https://dev.0chain.net/miner01"],"sharders":["https://dev.0chain.net/sharder01","https://dev.0chain.net/sharder02"]}
0chain-core-sdk [INFO]   2023/01/18 03:12:14.954317 wallet_base.go:255: Minimum sharders used for verify :1
0chain-core-sdk [INFO]   2023/01/18 03:12:14.954456 transaction_query_base.go:120: zcn: check health https://dev.0chain.net/sharder02/v1/healthcheck
0chain-core-sdk [DEBUG]  2023/01/18 03:12:16.105002 transaction_query_base.go:221: https://dev.0chain.net/sharder02/v1/screst/6dba10422e368813802877a85039d3985d96760ed844092319743fb3a76712d7/getUserStakePoolStat?client_id=95278eb5fe6bd13889a3aa09f1db69f0db2df47314fff1e2acce3f0a9fd79676 200 OK
0chain-core-sdk [DEBUG]  2023/01/18 03:12:16.105139 transaction_query_base.go:222: {"pools":{"7a90e6790bcd3d78422d7a230390edc102870fe58c15472073922024985b1c7d":[{"id":"95278eb5fe6bd13889a3aa09f1db69f0db2df47314fff1e2acce3f0a9fd79676","balance":10000000000,"delegate_id":"95278eb5fe6bd13889a3aa09f1db69f0db2df47314fff1e2acce3f0a9fd79676","rewards":0,"unstake":false,"provider_id":"","provider_type":0,"total_reward":0,"total_penalty":0,"status":"active","round_created":1293008}],"f65af5d64000c7cd2883f4910eb69086f9d6e6635c744e62afcfab58b938ee25":[{"id":"95278eb5fe6bd13889a3aa09f1db69f0db2df47314fff1e2acce3f0a9fd79676","balance":10000000000,"delegate_id":"95278eb5fe6bd13889a3aa09f1db69f0db2df47314fff1e2acce3f0a9fd79676","rewards":0,"unstake":false,"provider_id":"","provider_type":0,"total_reward":0,"total_penalty":0,"status":"active","round_created":1292968}]}}
- blobber_id:  7a90e6790bcd3d78422d7a230390edc102870fe58c15472073922024985b1c7d
  - id:                95278eb5fe6bd13889a3aa09f1db69f0db2df47314fff1e2acce3f0a9fd79676
    balance:           1.000 ZCN
    delegate_id:       95278eb5fe6bd13889a3aa09f1db69f0db2df47314fff1e2acce3f0a9fd79676
    unclaimed reward:        0 SAS
    total rewards:           0 SAS
    total penalty:           0 SAS
    status:           active
    round_created:    1293008
    unstake:          false
    staked_at:        0001-01-01 00:00:00 +0000 UTC
- blobber_id:  f65af5d64000c7cd2883f4910eb69086f9d6e6635c744e62afcfab58b938ee25
  - id:                95278eb5fe6bd13889a3aa09f1db69f0db2df47314fff1e2acce3f0a9fd79676
    balance:           1.000 ZCN
    delegate_id:       95278eb5fe6bd13889a3aa09f1db69f0db2df47314fff1e2acce3f0a9fd79676
    unclaimed reward:        0 SAS
    total rewards:           0 SAS
    total penalty:           0 SAS
    status:           active
    round_created:    1292968
    unstake:          false
    staked_at:        0001-01-01 00:00:00 +0000 UTC
```

### PR DESCRIPTION
**Pull request by pgrudra**
Changed data type of StakedAt attribute to keep consistency with 0chain

### CODE REVIEW

**Review by peterlimg — APPROVED** [review]
LGTM, please check if this change would affect the system test and update the system tests if any.

**Comment by service-0chain** [comment]
Manual system tests [cancelled] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | FALSE  |
| system-tests  | master  |
| gosdk  | 727-staked_at-is-incorrect-in-zbox-sp-user-info  |
| zboxcli  | staging  |
| zwalletcli  | staging  |
| 0chain  | staked_at-attribute-for-DelegatePoolStat  |
| blobber  | staging  |
| authorizer  | staging  |
| 0box  | staging  |
| 0block  | staging  |
| 0dns  | staging  |
| explorer  | staging  |
| 0proxy  | staging  |
| 0search  | staging  |

**Comment by service-0chain** [comment]
Manual system tests [failure] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | FALSE  |
| system-tests  | master  |
| gosdk  | 727-staked_at-is-incorrect-in-zbox-sp-user-info  |
| zboxcli  | staked-at-for-stake-pool-datatype-change  |
| zwalletcli  | staging  |
| 0chain  | staked_at-attribute-for-DelegatePoolStat  |
| blobber  | staging  |
| authorizer  | staging  |
| 0box  | staging  |
| 0block  | staging  |
| 0dns  | staging  |
| explorer  | staging  |
| 0proxy  | staging  |
| 0search  | staging  |

**Comment by service-0chain** [comment]
Manual system tests [success] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | TRUE  |
| system-tests  | master  |
| gosdk  | 727-staked_at-is-incorrect-in-zbox-sp-user-info  |
| zboxcli  | staging  |
| zwalletcli  | staging  |
| 0chain  | staging  |
| blobber  | staging  |
| authorizer  | staging  |
| 0box  | staging  |
| 0block  | staging  |
| 0dns  | staging  |
| explorer  | staging  |
| 0proxy  | staging  |
| 0search  | staging  |

**Pull request merged**
