### PR TITLE
Implement scrypt + chacha20poly1305

### LINKED ISSUE #770: feat: implement scrypt in js and go for mnemonics encryption
check detail [here](https://0chain.slack.com/archives/C028ZCJT6LU/p1671186132778049?thread_ts=1670934075.106909&cid=C028ZCJT6LU)

### PR DESCRIPTION
**Pull request by din-mukhammed**
### Version
- [x] Ensure to run `make getrev` to update gosdk version info.

### Changes
-

### Fixes
-

### Tests
Tasks to complete before merging PR:
- [ ]  Ensure system tests are passing. If not [Run them manually](https://github.com/0chain/gosdk/actions/workflows/system_tests.yml) to check for any regressions :clipboard:
- [ ]  Do any new system tests need added to test this change? do any existing system tests need updated? If so create a PR at [0chain/system_test](https://github.com/0chain/system_test)
- [ ]  Merge your system tests PR to master AFTER merging this PR

### Associated PRs (Link as appropriate):
- blobber:
- 0chain:
- system_test:
- zboxcli:
- zwalletcli:
- Other: ...

### CODE REVIEW

**Review by dabasov — APPROVED** [review]
lgtm

**Review by peterlimg — APPROVED** [review]
LGTM

**Comment by peterlimg** [comment]
Part of the unit tests will be fixed vai #847, the unit tests want to see rename success if the consensus blobbers provide a successful result, despite individual blobbers failing. However, recently changes make the rename process return error immediately when a single blobber gives error, which will make the consensus condition checking flaky.

**Comment by service-0chain** [comment]
Manual system tests [success] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | TRUE  |
| system-tests  | master  |
| gosdk  | 770-feat-implement-scrypt-in-js-and-go-for-mnemonics-encryption  |
| zboxcli  | staging  |
| zwalletcli  | staging  |
| 0chain  | staging  |
| blobber  | staging  |
| authorizer  | staging  |
| 0box  | staging  |
| 0block  | staging  |
| 0dns  | staging  |
| explorer  | staging  |
| 0proxy  | staging  |
| 0search  | staging  |

**Pull request merged**
