### PR TITLE
Fix empty FileID 

### PR DESCRIPTION
**Pull request by Hitenjain14**
### Fixes
New file should use fileID of the old file

### Tests
Tasks to complete before merging PR:
- [ ]  Ensure system tests are passing. If not [Run them manually](https://github.com/0chain/gosdk/actions/workflows/system_tests.yml) to check for any regressions :clipboard:
- [ ]  Do any new system tests need added to test this change? do any existing system tests need updated? If so create a PR at [0chain/system_test](https://github.com/0chain/system_test)
- [ ]  Merge your system tests PR to master AFTER merging this PR

### Associated PRs (Link as appropriate):
- blobber:  https://github.com/0chain/blobber/pull/1069
- 0chain:
- system_test:
- zboxcli:
- zwalletcli:
- Other: ...

### CODE REVIEW

**Review by lpoli — APPROVED** [review]

**Review by dabasov — APPROVED** [review]
lgtm

**Comment by service-0chain** [comment]
Manual system tests [failure] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | FALSE  |
| system-tests  | master  |
| gosdk  | fix/empty-id  |
| zboxcli  | fix/empty-id  |
| zwalletcli  | staging  |
| 0chain  | staging  |
| blobber  | fix/empty-id  |
| authorizer  | staging  |
| 0box  | staging  |
| 0dns  | staging  |

**Comment by service-0chain** [comment]
Manual system tests [failure] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | FALSE  |
| system-tests  | fix-empty-id  |
| gosdk  | fix/empty-id  |
| zboxcli  | fix/empty-id  |
| zwalletcli  | staging  |
| 0chain  | staging  |
| blobber  | fix/empty-id  |
| authorizer  | staging  |
| 0box  | staging  |
| 0dns  | staging  |

**Comment by service-0chain** [comment]
Manual system tests [cancelled] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | FALSE  |
| system-tests  | fix-empty-id  |
| gosdk  | fix/empty-id  |
| zboxcli  | fix/empty-id  |
| zwalletcli  | staging  |
| 0chain  | staging  |
| blobber  | fix/empty-id  |
| authorizer  | staging  |
| 0box  | staging  |
| 0dns  | staging  |

**Comment by service-0chain** [comment]
Manual system tests [success] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | FALSE  |
| system-tests  | fix-empty-id  |
| gosdk  | fix/empty-id  |
| zboxcli  | fix/empty-id  |
| zwalletcli  | staging  |
| 0chain  | staging  |
| blobber  | fix/empty-id  |
| authorizer  | staging  |
| 0box  | staging  |
| 0dns  | staging  |

**Pull request merged**
