### PR TITLE
Feature: provide audit zcnswap and refactor if needed

### LINKED ISSUE #1202: Feature: provide audit zcnswap and refactor if needed
Currently zcnswap contains some logic, but there are no tests and some of it might be out-dated

### PR DESCRIPTION
**Pull request by YarikRevich**
* Simplifies and moves swap logic to bridge
* Updates Bancor smart contracts to V3

# Associated PRs
* https://github.com/0chain/zwalletcli/pull/316

### CODE REVIEW

**Review by peterlimg — APPROVED** [review]
LGTM

**Comment by service-0chain** [comment]
Manual system tests [failure] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | false  |
| system-tests  |   |
| gosdk  | feature/zcnswap  |
| zboxcli  |   |
| zwalletcli  |   |
| 0chain  |   |
| blobber  |   |
| authorizer  |   |
| 0box  |   |
| 0dns  |   |

**Comment by service-0chain** [comment]
Manual system tests [cancelled] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | false  |
| system-tests  |   |
| gosdk  | feature/zcnswap  |
| zboxcli  |   |
| zwalletcli  |   |
| 0chain  |   |
| blobber  |   |
| authorizer  |   |
| 0box  |   |
| 0dns  |   |

**Comment by service-0chain** [comment]
Manual system tests [success] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | false  |
| system-tests  |   |
| gosdk  | feature/zcnswap  |
| zboxcli  |   |
| zwalletcli  |   |
| 0chain  |   |
| blobber  |   |
| authorizer  |   |
| 0box  |   |
| 0dns  |   |

**Pull request merged**
