### PR TITLE
Wrongly init storagesdk method

### PR DESCRIPTION
**Pull request by moldis**
These changes resolving the issue for initializing clients Apps as well as 0proxy

Related to this PR: https://github.com/0chain/gosdk/pull/217

### CODE REVIEW

**Review by cnlangzi — APPROVED** [review]
LGTM

**Comment by Rizary** [comment]
@moldis can we also run `zcncore.Init` inside this `InitSorageSDK` so we can simplify the code in the wasm part?

**Comment by cnlangzi** [comment]
@moldis I have moved it from zboxcore.InitStorageSDK. It will get values from zcncore._config.Chain and zboxcore.blockchain  automatically. do you think it is better?

**Comment by cnlangzi** [comment]
@moldis  it is fixed on https://github.com/0chain/gosdk/pull/257. please double test it. thanks.

**Comment by moldis** [comment]
Closing as it's fixed in another branch

**Pull request closed without merging**
