### PR TITLE
Modify/read marker

### PR DESCRIPTION
**Pull request by lpoli**
This PR contains following changes:
1. Change ReadMarker fields to `ReadSize` from `ReadCounter`
2. Remove logic that considers previous/latest readmarker

### CODE REVIEW

**Review by stewartie4 — APPROVED** [review]
Approved on behalf of

**Review by stewartie4 — APPROVED** [review]
Approved on behalf of

**Review by dabasov — APPROVED** [review]
lgtm

**Comment by service-0chain** [comment]
Manual system tests [success] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | FALSE  |
| system-tests  | fix/download-cost-calculation  |
| gosdk  | modify/read-marker  |
| zboxcli  | modify/read-marker  |
| zwalletcli  | staging  |
| 0chain  | modify/read-marker  |
| blobber  | modify/read-marker2  |
| authorizer  | staging  |
| 0box  | staging  |
| 0block  | staging  |
| 0dns  | staging  |
| explorer  | staging  |
| 0proxy  | staging  |
| 0search  | staging  |

**Pull request merged**
