### PR TITLE
Swagger changes

### PR DESCRIPTION
**Pull request by Sriep**
### Changes
-swagger does not allow multiple identical endpoint names, even if the paths are different. Hence changing `getConfig` endpoint names.

### Fixes
-

### Tests
Tasks to complete before merging PR:
- [ ]  Ensure system tests are passing. If not [Run them manually](https://github.com/0chain/gosdk/actions/workflows/system_tests.yml) to check for any regressions :clipboard:
- [ ]  Do any new system tests need added to test this change? do any existing system tests need updated? If so create a PR at [0chain/system_test](https://github.com/0chain/system_test)
- [ ]  Merge your system tests PR to master AFTER merging this PR

### Associated PRs (Link as appropriate):
- blobber:
- 0chain: https://github.com/0chain/0chain/pull/1304
- system_test:
- zboxcli:
- zwalletcli:
- Other: ...

### CODE REVIEW

**Comment by service-0chain** [comment]
Manual system tests [failure] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | FALSE  |
| system-tests  | master  |
| gosdk  | swagger  |
| zboxcli  | staging  |
| zwalletcli  | staging  |
| 0chain  | restapi_refactor  |
| blobber  | staging  |
| authorizer  | staging  |
| 0box  | staging  |
| 0block  | staging  |
| 0dns  | staging  |
| explorer  | staging  |
| 0proxy  | staging  |
| 0search  | staging  |

**Comment by service-0chain** [comment]
Manual system tests [failure] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | FALSE  |
| system-tests  | master  |
| gosdk  | swagger  |
| zboxcli  | staging  |
| zwalletcli  | staging  |
| 0chain  | staging  |
| blobber  | staging  |
| authorizer  | staging  |
| 0box  | staging  |
| 0block  | staging  |
| 0dns  | staging  |
| explorer  | staging  |
| 0proxy  | staging  |
| 0search  | staging  |

**Comment by cnlangzi** [comment]
cc @shaktals  please check it on js-client-sdk too.

**Comment by shaktals** [comment]
@cnlangzi thanks for the heads up! The getConfig endpoint is not used on js-client-sdk, nor on web-apps for now.

**Comment by service-0chain** [comment]
Manual system tests [success] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | FALSE  |
| system-tests  | master  |
| gosdk  | swagger  |
| zboxcli  | staging  |
| zwalletcli  | staging  |
| 0chain  | restapi_refactor  |
| blobber  | staging  |
| authorizer  | staging  |
| 0box  | staging  |
| 0block  | staging  |
| 0dns  | staging  |
| explorer  | staging  |
| 0proxy  | staging  |
| 0search  | staging  |

**Review by Kishan-Dhakan — APPROVED** [review]
- We are not very consistent with our endpoints (unless I'm missing something), for example:

```
"/getReadPoolStat",
"/getReadPoolAllocBlobberStat",
"/getWritePoolStat",
"/getWritePoolAllocBlobberStat",
"/getChallengePoolStat",

"/alloc_written_size",
"/alloc_read_size",
"/alloc_write_marker_count",
"/collected_reward",
"/blobber_ids",
```

- We should decide on what suits us the best, and use the same style going forward. This will minimize work in the future should we decide to clean this.

**Comment by service-0chain** [comment]
Manual system tests [failure] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | FALSE  |
| system-tests  | fix/broken_owner_test  |
| gosdk  | staging  |
| zboxcli  | fix/get_config  |
| zwalletcli  | fix/get_config  |
| 0chain  | staging  |
| blobber  | staging  |
| authorizer  | staging  |
| 0box  | staging  |
| 0block  | staging  |
| 0dns  | staging  |
| explorer  | staging  |
| 0proxy  | staging  |
| 0search  | staging  |

**Comment by service-0chain** [comment]
Manual system tests [success] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | FALSE  |
| system-tests  | fix/broken_owner_test  |
| gosdk  | staging  |
| zboxcli  | fix/get_config  |
| zwalletcli  | fix/get_config  |
| 0chain  | staging  |
| blobber  | staging  |
| authorizer  | staging  |
| 0box  | staging  |
| 0block  | staging  |
| 0dns  | staging  |
| explorer  | staging  |
| 0proxy  | staging  |
| 0search  | staging  |

**Pull request merged**
