### PR TITLE
chore: Revert "Feature/bridge wasm" to fix broken staging

### PR DESCRIPTION
**Pull request by Kishan-Dhakan**
Reverts 0chain/gosdk#547

### CODE REVIEW

**Comment by service-0chain** [comment]
Manual system tests [failure] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | FALSE  |
| system-tests  | master  |
| gosdk  | revert-547-feature/bridge-wasm  |
| zboxcli  | staging  |
| zwalletcli  | staging  |
| 0chain  | staging  |
| blobber  | staging  |
| authorizer  | staging  |
| 0box  | staging  |
| 0block  | staging  |
| 0dns  | staging  |
| explorer  | staging  |
| 0proxy  | staging  |
| 0search  | staging  |

**Comment by cnlangzi** [comment]
@Kishan-Dhakan  it only applies changes on wasm/bridge. it should not break it. let me check it

**Comment by cnlangzi** [comment]
fixed it on https://github.com/0chain/zwalletcli/pull/177

**Comment by cnlangzi** [comment]
it is fixed

**Pull request closed without merging**
