### PR TITLE
Feature/available after param

### PR DESCRIPTION
**Pull request by rizary**
re-PR this feature since it is not this commit fault that caused system_test failing

- blobber: https://github.com/0chain/blobber/pull/442
- gosdk: https://github.com/0chain/gosdk/pull/331
- zbox: https://github.com/0chain/zboxcli/pull/131
- system_test: https://github.com/0chain/system_test/pull/122

### CODE REVIEW

**Review by moldis — APPROVED** [review]
Looks good

**Comment by cnlangzi** [comment]
@Rizary please check and fix https://github.com/0chain/zboxcli/pull/131 too

**Comment by service-0chain** [comment]
Manual system tests [failure] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | FALSE  |
| system-tests  | feature/zboxcli-available-after  |
| gosdk  | feature/available-after-param  |
| zboxcli  | feature/available-after-param  |
| zwalletcli  | staging  |
| 0chain  | staging  |
| blobber  | pr-442-24b649ee  |
| 0box  | feature/available-after-param  |
| 0block  | staging  |
| 0dns  | staging  |
| explorer  | staging  |
| 0proxy  | staging  |
| 0search  | staging  |

**Comment by service-0chain** [comment]
Manual system tests [failure] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | FALSE  |
| system-tests  | feature/available-after-param  |
| gosdk  | feature/available-after-param  |
| zboxcli  | feature/available-after-param  |
| zwalletcli  | staging  |
| 0chain  | staging  |
| blobber  | pr-442-24b649ee  |
| authorizer  | staging  |
| 0box  | feature/available-after-param  |
| 0block  | staging  |
| 0dns  | staging  |
| explorer  | staging  |
| 0proxy  | staging  |
| 0search  | staging  |

**Comment by service-0chain** [comment]
Manual system tests [failure] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | FALSE  |
| system-tests  | feature/zboxcli-available-after  |
| gosdk  | feature/available-after-param  |
| zboxcli  | feature/zboxcli-available-after  |
| zwalletcli  | staging  |
| 0chain  | staging  |
| blobber  | feature/zboxcli-available-after  |
| authorizer  | staging  |
| 0box  | feature/zboxcli-available-after  |
| 0block  | staging  |
| 0dns  | staging  |
| explorer  | staging  |
| 0proxy  | staging  |
| 0search  | staging  |

**Comment by cnlangzi** [comment]
@Rizary  there is a breaking change on wasm from https://github.com/0chain/gosdk/pull/331/commits/aba106051571e541ecb5de3b13c27751a6c9825c . please raise an issue on 0chain/block-explorer to upgrade it too, and ping @shaktals  @chauchausoup 
and don't forget to update ./wasmsdk/README.md

**Comment by service-0chain** [comment]
Manual system tests [failure] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | FALSE  |
| system-tests  | feature/zboxcli-available-after  |
| gosdk  | feature/available-after-param  |
| zboxcli  | feature/available-after-param  |
| zwalletcli  | staging  |
| 0chain  | staging  |
| blobber  | feature/available-after-param  |
| authorizer  | staging  |
| 0box  | staging  |
| 0block  | staging  |
| 0dns  | staging  |
| explorer  | staging  |
| 0proxy  | staging  |
| 0search  | staging  |

**Comment by service-0chain** [comment]
Manual system tests [failure] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | FALSE  |
| system-tests  | feature/zboxcli-available-after  |
| gosdk  | feature/available-after-param  |
| zboxcli  | feature/available-after-param  |
| zwalletcli  | staging  |
| 0chain  | staging  |
| blobber  | pr-442-76b882e5  |
| authorizer  | staging  |
| 0box  | staging  |
| 0block  | staging  |
| 0dns  | staging  |
| explorer  | staging  |
| 0proxy  | staging  |
| 0search  | staging  |

**Comment by cnlangzi** [comment]
it is fixed on https://github.com/0chain/gosdk/pull/418

**Pull request closed without merging**
