### PR TITLE
get only active blobbers in sdk.GetBlobbers()

### PR DESCRIPTION
**Pull request by boddumanohar**
### Changes

the get blobbers API is paginated:
https://github.com/0chain/0chain/blob/6d50f2192b39ccb23abcc6d8545c1e5e2c9bd1ff/code/go/0chain.net/smartcontract/storagesc/handler.go#L2254-L2268

in sdk.GetBlobbers() we are only getting the latest 20 blobbers. This information might not be useful. So recently a change was made to `/getblobbers` to get only the active blobbers

https://github.com/0chain/0chain/pull/1754

after this change `sdk.GetBlobbers()` will return the blobbers which are active since the last 5 mins

### Fixes
-

### Tests
Tasks to complete before merging PR:
- [ ]  Ensure system tests are passing. If not [Run them manually](https://github.com/0chain/gosdk/actions/workflows/system_tests.yml) to check for any regressions :clipboard:
- [ ]  Do any new system tests need added to test this change? do any existing system tests need updated? If so create a PR at [0chain/system_test](https://github.com/0chain/system_test)
- [ ]  Merge your system tests PR to master AFTER merging this PR

### Associated PRs (Link as appropriate):
- blobber:
- 0chain:
- system_test:
- zboxcli:
- zwalletcli:
- Other: ...

### CODE REVIEW

**Comment by cnlangzi** [comment]
@boddumanohar  it should break `./zbox ls-blobbers --all`. please check and fix it too

**Comment by boddumanohar** [comment]
`zbox ls-blobbers` is supposed to show all the active blobbers

https://github.com/0chain/zboxcli/blob/eccc61f117902420af18029dd42cfa85247d6c0d/cmd/storage.go#L109-L110

what doesn't `all`flag means for `zbox ls-blobbers`?

**Comment by cnlangzi** [comment]
> `zbox ls-blobbers` is supposed to show all the active blobbers
> 
> https://github.com/0chain/zboxcli/blob/eccc61f117902420af18029dd42cfa85247d6c0d/cmd/storage.go#L109-L110
> 
> what doesn't `all`flag means for `zbox ls-blobbers`?

see detail in [code](https://github.com/0chain/zboxcli/blob/a0e9585a7845f8a22b04b6b5c933374a7fdd5013/cmd/storage.go#L110). active filter is applied in zboxcli instead of remote api. for now , it is done by remote api. so it is impossible to show all blobbers whatever it is offline in zbox now. --all filter should be removed from zobx, or added in remote api.

**Comment by boddumanohar** [comment]
> see detail in code. active filter is applied in zboxcli instead of remote api.

the current problem is we /getblobbers doesn't use pagination because of this, it only gets first 20 and we are running `filterActiveBlobbers` on those 2 blobbers we received. 

So we should either do pagination from the zbox side and use this [filterActiveBlobbers](https://github.com/0chain/zboxcli/blob/a0e9585a7845f8a22b04b6b5c933374a7fdd5013/cmd/storage.go#L110) to filter active blobbers

or else we can use `/getblobbers?active=true` to get active blobbers. 

we could also create a new function `GetActiveBlobbers` that gets only the active blobbers and modify the `ls-blobbers` logic to use this function. Instead of modifying the `sdk.GetBlobbers`function.

**Comment by cnlangzi** [comment]
@boddumanohar  I'd prefer to filter them on remote api instead local method.

**Comment by boddumanohar** [comment]
@cnlangzi  to do that filtering, I have recently added a change in 0chain https://github.com/0chain/0chain/pull/1754

since we are doing this on the 0chain side now, [this piece of code](https://github.com/0chain/zboxcli/blob/eccc61f117902420af18029dd42cfa85247d6c0d/cmd/storage.go#L109-L110) that you pointed out will definitely pass because:

In the 0chain side active blobbers are filtered within [5 mins interval](https://github.com/0chain/0chain/blob/e13c91b3c6964126220c1ce457e786921c0abec4/code/go/0chain.net/smartcontract/dbs/event/blobber.go#L17-L18)

In the gosdk side, the active blobbers are filters with 1 hour range.

**Review by cnlangzi — APPROVED** [review]
LGTM

**Comment by cnlangzi** [comment]
@boddumanohar  please don't forget to update zbox 
`./zbox ls-blobbers` and `./zbox ls-bobbers --all`. they don't work properly now.  for now, `./zbox ls-blobbers --all` also only gets active blobbers instead of all blobbers

**Review by peterlimg — APPROVED** [review]

**Comment by service-0chain** [comment]
Manual system tests [success] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | TRUE  |
| system-tests  | master  |
| gosdk  | get-activeblobbers  |
| zboxcli  | staging  |
| zwalletcli  | staging  |
| 0chain  | staging  |
| blobber  | staging  |
| authorizer  | staging  |
| 0box  | staging  |
| 0block  | staging  |
| 0dns  | staging  |
| explorer  | staging  |
| 0proxy  | staging  |
| 0search  | staging  |

**Pull request merged**
