### PR TITLE
Integrating with pkg/errors

### PR DESCRIPTION
**Pull request by NoSkillGuy**
**Changes**:
1. using https://github.com/pkg/errors instead of our self implementation of errors!

### CODE REVIEW

**Review by kushthedude — COMMENTED** [review]
Aren't you doing same thing here? Why to implement Wrap & Error struct when pkg/error has got everything. Just rip off the `core/common/errors` & use pkg/errors everywhere. Else there is no difference in this implementation & the older, its just redundant change to again give a wrapper over already implemented functionality.

**Comment by NoSkillGuy** [comment]
@kushthedude we want to have our application error to have code and message.

**Comment by NoSkillGuy** [comment]
@kushthedude this error package would wrap on `pkg/errors`. Here we can have some standard errors for the application.

**Comment by NoSkillGuy** [comment]
Closing this PR in favour of https://github.com/0chain/gosdk/pull/196

**Pull request closed without merging**
