### PR TITLE
FEAT_ADD Pagination When Retrieving Miners and Sharders List

### LINKED ISSUE #203: ls-miners and ls-sharders only return first 20
Due to pagination on SDK only first 20 are returned, CLI should either combine the multiple offset pages and return combined list or add offset or pagination to obtain full list.

### PR DESCRIPTION
**Pull request by K-Kumar-01**
### Changes
- Update GetMiners and GetSharders function

### Why this PR
- To implement and fix [this](https://github.com/0chain/zwalletcli/issues/203), there was a need to update the underlying functions present in this Repo.

### Tests
Tasks to complete before merging PR:
- [ ]  Ensure system tests are passing. If not [Run them manually](https://github.com/0chain/gosdk/actions/workflows/system_tests.yml) to check for any regressions :clipboard:
- [ ]  Do any new system tests need added to test this change? do any existing system tests need updated? If so create a PR at [0chain/system_test](https://github.com/0chain/system_test)
- [ ]  Merge your system tests PR to master AFTER merging this PR

### CODE REVIEW

**Review by peterlimg — DISMISSED** [review]
@K-Kumar-01 can you update the client ends including zboxcli and wasm if any to adjust the changes.

**Comment by service-0chain** [comment]
Manual system tests [failure] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | FALSE  |
| system-tests  | master  |
| gosdk  | k-kumar-01/feat/miners-and-sharders-list-functions-update  |
| zboxcli  | staging  |
| zwalletcli  | k-kumar-01/i203/add-pagination-miners-and-sharders  |
| 0chain  | staging  |
| blobber  | staging  |
| authorizer  | staging  |
| 0box  | staging  |
| 0block  | staging  |
| 0dns  | staging  |
| explorer  | staging  |
| 0proxy  | staging  |
| 0search  | staging  |

**Comment by service-0chain** [comment]
Manual system tests [failure] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | ABILITY TO SKIP TESTS IS DISABLED. SKIP_TESTS OPTION IGNORED.  |
| system-tests  | pagination-pr  |
| gosdk  | k-kumar-01/feat/miners-and-sharders-list-functions-update  |
| zboxcli  | staging  |
| zwalletcli  | k-kumar-01/i203/add-pagination-miners-and-sharders  |
| 0chain  | staging  |
| blobber  | staging  |
| authorizer  | staging  |
| 0box  | staging  |
| 0block  | staging  |
| 0dns  | staging  |
| explorer  | staging  |
| 0proxy  | staging  |
| 0search  | staging  |

**Comment by service-0chain** [comment]
Manual system tests [success] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | ABILITY TO SKIP TESTS IS DISABLED. SKIP_TESTS OPTION IGNORED.  |
| system-tests  | pagination-pr  |
| gosdk  | k-kumar-01/feat/miners-and-sharders-list-functions-update  |
| zboxcli  | staging  |
| zwalletcli  | k-kumar-01/i203/add-pagination-miners-and-sharders  |
| 0chain  | staging  |
| blobber  | staging  |
| authorizer  | staging  |
| 0box  | staging  |
| 0block  | staging  |
| 0dns  | staging  |
| explorer  | staging  |
| 0proxy  | staging  |
| 0search  | staging  |

**Review by Kishan-Dhakan — APPROVED** [review]

**Review by dabasov — APPROVED** [review]
lgtm

**Pull request merged**
