### PR TITLE
Fix performance issue in getting a random slice of size n from an input slice

### LINKED ISSUE #748: Improve performance of `GetRandom` for generating random sequence of miners and sharders
The current implementation of generating a random slice from an input looks something like this:
https://github.com/0chain/gosdk/blob/7140de11080e5b2e45fd6545a0fb662b77fd713f/core/util/rand.go#L57-L72

This is worst case O(n^2), and can hamper the performance when there are lots of miners and sharders. This can be improved and brought down to O(n) which will help with the performance.

cc: @dabasov

### PR DESCRIPTION
**Pull request by aniketsingh03**
### Changes
This is the same as #749  but with the compare branch changed from fork to upstream. 
This PR improves the performance of generating a random slice of size 'n' from an input slice, from O(n^2) to O(n). This will significantly improve performance when there are lots of miners/sharders in the network.

### Fixes
Fixes https://github.com/0chain/gosdk/issues/748

### Tests
Tasks to complete before merging PR:
- [ ]  Ensure system tests are passing. If not [Run them manually](https://github.com/0chain/gosdk/actions/workflows/system_tests.yml) to check for any regressions :clipboard:
- [ ]  Do any new system tests need added to test this change? do any existing system tests need updated? If so create a PR at [0chain/system_test](https://github.com/0chain/system_test)
- [ ]  Merge your system tests PR to master AFTER merging this PR

### Associated PRs (Link as appropriate):
- blobber:
- 0chain:
- system_test:
- zboxcli:
- zwalletcli:
- Other: ...

### CODE REVIEW

**Comment by service-0chain** [comment]
Manual system tests [success] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | FALSE  |
| system-tests  | master  |
| gosdk  | performance/GetRandom  |
| zboxcli  | staging  |
| zwalletcli  | staging  |
| 0chain  | staging  |
| blobber  | staging  |
| authorizer  | staging  |
| 0box  | staging  |
| 0block  | staging  |
| 0dns  | staging  |
| explorer  | staging  |
| 0proxy  | staging  |
| 0search  | staging  |

**Comment by aniketsingh03** [comment]
Can you review this @peterlimg and @dabasov? This is same as #749  but the branch is in upstream as system tests weren't running earlier.

**Review by peterlimg — APPROVED** [review]
LGTM

**Comment by service-0chain** [comment]
Manual system tests [success] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | true  |
| system-tests  | master  |
| gosdk  | performance/GetRandom  |
| zboxcli  | staging  |
| zwalletcli  | staging  |
| 0chain  | staging  |
| blobber  | staging  |
| authorizer  | staging  |
| 0box  | staging  |
| 0block  | staging  |
| 0dns  | staging  |
| explorer  | staging  |
| 0proxy  | staging  |
| 0search  | staging  |

**Pull request merged**
