### PR TITLE
Update ref.go

### PR DESCRIPTION
**Pull request by abouroumine**
### Changes
- This is a PR due to this blobber PR https://github.com/0chain/blobber/pull/529 please don't merge or anything until the blobber PR is finished.
- It Modifies the CalculateHash depending on the PR https://github.com/0chain/blobber/pull/529 requirement

### Fixes
-

### Tests
Tasks to complete before merging PR:
- [ ]  Ensure system tests are passing. If not [Run them manually](https://github.com/0chain/gosdk/actions/workflows/system_tests.yml) to check for any regressions :clipboard:
- [ ]  Do any new system tests need added to test this change? do any existing system tests need updated? If so create a PR at [0chain/system_test](https://github.com/0chain/system_test)
- [ ]  Merge your system tests PR to master AFTER merging this PR

### Associated PRs (Link as appropriate):
- blobber: https://github.com/0chain/blobber/pull/529
- 0chain:
- system_test: https://github.com/0chain/system_test/pull/218
- zboxcli: https://github.com/0chain/zboxcli/pull/192
- zwalletcli:
- Other: ...

### CODE REVIEW

**Review by lpoli — APPROVED** [review]

**Comment by service-0chain** [comment]
Manual system tests [failure] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | FALSE  |
| system-tests  | master  |
| gosdk  | blobber/issue-524  |
| zboxcli  | blobber/issue-524  |
| zwalletcli  | staging  |
| 0chain  | staging  |
| blobber  | issue/524  |
| authorizer  | staging  |
| 0box  | staging  |
| 0block  | staging  |
| 0dns  | staging  |
| explorer  | staging  |
| 0proxy  | staging  |
| 0search  | staging  |

**Comment by service-0chain** [comment]
Manual system tests [success] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | FALSE  |
| system-tests  | master  |
| gosdk  | blobber/issue-524  |
| zboxcli  | blobber/issue-524  |
| zwalletcli  | staging  |
| 0chain  | staging  |
| blobber  | issue/524  |
| authorizer  | staging  |
| 0box  | staging  |
| 0block  | staging  |
| 0dns  | staging  |
| explorer  | staging  |
| 0proxy  | staging  |
| 0search  | staging  |

**Comment by service-0chain** [comment]
Manual system tests [failure] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | FALSE  |
| system-tests  | blobber/issue-524  |
| gosdk  | blobber/issue-524  |
| zboxcli  | blobber/issue-524  |
| zwalletcli  | staging  |
| 0chain  | staging  |
| blobber  | issue/524  |
| authorizer  | staging  |
| 0box  | staging  |
| 0block  | staging  |
| 0dns  | staging  |
| explorer  | staging  |
| 0proxy  | staging  |
| 0search  | staging  |

**Comment by service-0chain** [comment]
Manual system tests [success] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | FALSE  |
| system-tests  | blobber/issue-524  |
| gosdk  | blobber/issue-524  |
| zboxcli  | blobber/issue-524  |
| zwalletcli  | staging  |
| 0chain  | staging  |
| blobber  | issue/524  |
| authorizer  | staging  |
| 0box  | staging  |
| 0block  | staging  |
| 0dns  | staging  |
| explorer  | staging  |
| 0proxy  | staging  |
| 0search  | staging  |

**Review by peterlimg — APPROVED** [review]
lgtm

**Review by moldis — APPROVED** [review]

**Review by moldis — APPROVED** [review]

**Comment by service-0chain** [comment]
Manual system tests [success] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | FALSE  |
| system-tests  | master  |
| gosdk  | staging  |
| zboxcli  | staging  |
| zwalletcli  | staging  |
| 0chain  | staging  |
| blobber  | staging  |
| authorizer  | staging  |
| 0box  | staging  |
| 0block  | staging  |
| 0dns  | staging  |
| explorer  | staging  |
| 0proxy  | staging  |
| 0search  | staging  |

**Pull request merged**
