### PR TITLE
Remove user write pools

### PR DESCRIPTION
**Pull request by Sriep**
### Changes
- Remove user write pool code as required by https://github.com/0chain/0chain/pull/1373. Do not merge without PR1373.

### Fixes
-

### Tests
Tasks to complete before merging PR:
- [ ]  Ensure system tests are passing. If not [Run them manually](https://github.com/0chain/gosdk/actions/workflows/system_tests.yml) to check for any regressions :clipboard:
- [ ]  Do any new system tests need added to test this change? do any existing system tests need updated? If so create a PR at [0chain/system_test](https://github.com/0chain/system_test)
- [ ]  Merge your system tests PR to master AFTER merging this PR

### Associated PRs (Link as appropriate):
- blobber:https://github.com/0chain/blobber/pull/725
- 0chain: https://github.com/0chain/0chain/pull/1465
- system_test: https://github.com/0chain/system_test/pull/315
- zboxcli:https://github.com/0chain/zboxcli/pull/258
- zwalletcli:
- Other: ...

### CODE REVIEW

**Comment by service-0chain** [comment]
Manual system tests [failure] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | FALSE  |
| system-tests  | master  |
| gosdk  | remove_write_pools  |
| zboxcli  | remove_write_pools  |
| zwalletcli  | staging  |
| 0chain  | remove_write_pools  |
| blobber  | remove_write_pools  |
| authorizer  | staging  |
| 0box  | staging  |
| 0block  | staging  |
| 0dns  | staging  |
| explorer  | staging  |
| 0proxy  | staging  |
| 0search  | staging  |

**Comment by service-0chain** [comment]
Manual system tests [failure] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | FALSE  |
| system-tests  | master  |
| gosdk  | remove_write_pools  |
| zboxcli  | remove_write_pool  |
| zwalletcli  | staging  |
| 0chain  | remove_write_pools  |
| blobber  | remove_write_pools  |
| authorizer  | staging  |
| 0box  | staging  |
| 0block  | staging  |
| 0dns  | staging  |
| explorer  | staging  |
| 0proxy  | staging  |
| 0search  | staging  |

**Comment by service-0chain** [comment]
Manual system tests [failure] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | FALSE  |
| system-tests  | remove/writepool  |
| gosdk  | remove_write_pools  |
| zboxcli  | remove_write_pool  |
| zwalletcli  | staging  |
| 0chain  | remove_write_pools  |
| blobber  | remove_write_pools  |
| authorizer  | staging  |
| 0box  | staging  |
| 0block  | staging  |
| 0dns  | staging  |
| explorer  | staging  |
| 0proxy  | staging  |
| 0search  | staging  |

**Comment by service-0chain** [comment]
Manual system tests [failure] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | FALSE  |
| system-tests  | remove/writepool  |
| gosdk  | remove_write_pools  |
| zboxcli  | remove_write_pool  |
| zwalletcli  | staging  |
| 0chain  | write_pools  |
| blobber  | remove_write_pools  |
| authorizer  | staging  |
| 0box  | staging  |
| 0block  | staging  |
| 0dns  | staging  |
| explorer  | staging  |
| 0proxy  | staging  |
| 0search  | staging  |

**Comment by service-0chain** [comment]
Manual system tests [failure] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | FALSE  |
| system-tests  | remove/writepool  |
| gosdk  | remove_write_pools  |
| zboxcli  | staging  |
| zwalletcli  | staging  |
| 0chain  | write_pools  |
| blobber  | remove_write_pools  |
| authorizer  | staging  |
| 0box  | staging  |
| 0block  | staging  |
| 0dns  | staging  |
| explorer  | staging  |
| 0proxy  | staging  |
| 0search  | staging  |

**Comment by service-0chain** [comment]
Manual system tests [success] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | FALSE  |
| system-tests  | remove/writepool  |
| gosdk  | remove_write_pools  |
| zboxcli  | remove_write_pool  |
| zwalletcli  | staging  |
| 0chain  | write_pools  |
| blobber  | remove_write_pools  |
| authorizer  | staging  |
| 0box  | staging  |
| 0block  | staging  |
| 0dns  | staging  |
| explorer  | staging  |
| 0proxy  | staging  |
| 0search  | staging  |

**Review by peterlimg — APPROVED** [review]
lgtm

**Comment by service-0chain** [comment]
Manual system tests [failure] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | FALSE  |
| system-tests  | remove/writepool  |
| gosdk  | remove_write_pools  |
| zboxcli  | remove_write_pool  |
| zwalletcli  | staging  |
| 0chain  | remove_write_pool  |
| blobber  | remove_write_pools  |
| authorizer  | staging  |
| 0box  | staging  |
| 0block  | staging  |
| 0dns  | staging  |
| explorer  | staging  |
| 0proxy  | staging  |
| 0search  | staging  |

**Comment by service-0chain** [comment]
Manual system tests [failure] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | FALSE  |
| system-tests  | master  |
| gosdk  | remove_write_pools  |
| zboxcli  | remove_write_pool  |
| zwalletcli  | staging  |
| 0chain  | write_pools  |
| blobber  | remove_write_pools  |
| authorizer  | staging  |
| 0box  | staging  |
| 0block  | staging  |
| 0dns  | staging  |
| explorer  | staging  |
| 0proxy  | staging  |
| 0search  | staging  |

**Comment by service-0chain** [comment]
Manual system tests [success] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | TRUE  |
| system-tests  | master  |
| gosdk  | remove_write_pools  |
| zboxcli  | staging  |
| zwalletcli  | staging  |
| 0chain  | staging  |
| blobber  | staging  |
| authorizer  | staging  |
| 0box  | staging  |
| 0block  | staging  |
| 0dns  | staging  |
| explorer  | staging  |
| 0proxy  | staging  |
| 0search  | staging  |

**Pull request merged**
